// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateItem(ctx context.Context, arg CreateItemParams) (Item, error)
	DeleteItem(ctx context.Context, arg DeleteItemParams) error
	GetItem(ctx context.Context, arg GetItemParams) (Item, error)
	ListItems(ctx context.Context, arg ListItemsParams) ([]Item, error)
}

var _ Querier = (*Queries)(nil)
